### ISSUE TITLE
Glusterdeployment fails on oVirt Node 4.5.4.1

### ISSUE THREAD

**Issue by Red-Ex** [oVirt/cockpit-ovirt#38]
During the deployment the process fails with

`TASK [gluster.infra/roles/backend_setup : Group devices by volume group name, including existing devices] ***
task path: /etc/ansible/roles/gluster.infra/roles/backend_setup/tasks/get_vg_groupings.yml:3
fatal: [brick001.storage.hellebar.de]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'str object' has no attribute 'vgname'\n\nThe error appears to be in '/etc/ansible/roles/gluster.infra/roles/backend_setup/tasks/get_vg_groupings.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Group devices by volume group name, including existing devices\n  ^ here\n"}`

I assume, that this is relaying on the newer ansible version. I tried to change that part to volume_groups.vgname but that doesn't work. 
The same process works on oVirt 4.5.3.2 as expected.
